<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Initial schema, PostgreSQL search (unaccent, pg_trgm, French tsvector), sessions and messenger tables.
 */
final class Version20261008174358 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema with full-text search, sessions and messenger tables';
    }

    public function up(Schema $schema): void
    {
        // "unaccent" and "pg_trgm" are trusted extensions: the database owner can create them.
        $this->addSql('CREATE EXTENSION IF NOT EXISTS unaccent');
        $this->addSql('CREATE EXTENSION IF NOT EXISTS pg_trgm');
        $this->addSql('CREATE TEXT SEARCH CONFIGURATION ariane_fr (COPY = french)');
        $this->addSql('ALTER TEXT SEARCH CONFIGURATION ariane_fr ALTER MAPPING FOR hword, hword_part, word WITH unaccent, french_stem');

        $this->addSql('CREATE TABLE audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, actor_label VARCHAR(200) NOT NULL, action VARCHAR(60) NOT NULL, target_type VARCHAR(60) DEFAULT NULL, target_id VARCHAR(64) DEFAULT NULL, details JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_audit_log_created_at ON audit_log (created_at)');
        $this->addSql('CREATE INDEX IDX_F6E1C0F510DAF24A ON audit_log (actor_id)');
        $this->addSql('CREATE TABLE change_request (id UUID NOT NULL, type VARCHAR(20) NOT NULL, payload JSON NOT NULL, proposer_name VARCHAR(100) NOT NULL, status VARCHAR(20) NOT NULL, review_comment TEXT DEFAULT NULL, quarantine_key VARCHAR(64) DEFAULT NULL, quarantine_size BIGINT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, document_id UUID DEFAULT NULL, proposer_user_id INT DEFAULT NULL, reviewer_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_change_request_status ON change_request (status)');
        $this->addSql('CREATE INDEX IDX_CB902D36C33F7837 ON change_request (document_id)');
        $this->addSql('CREATE INDEX IDX_CB902D369F23DA47 ON change_request (proposer_user_id)');
        $this->addSql('CREATE INDEX IDX_CB902D3670574616 ON change_request (reviewer_id)');
        $this->addSql('CREATE TABLE document (id UUID NOT NULL, title VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, tags_text TEXT DEFAULT \'\' NOT NULL, kind VARCHAR(20) NOT NULL, storage_key VARCHAR(64) DEFAULT NULL, original_filename VARCHAR(255) DEFAULT NULL, mime_type VARCHAR(120) DEFAULT NULL, size BIGINT DEFAULT NULL, sha256 VARCHAR(64) DEFAULT NULL, external_url VARCHAR(500) DEFAULT NULL, preview_key VARCHAR(80) DEFAULT NULL, extracted_text TEXT DEFAULT NULL, search_vector TSVECTOR DEFAULT NULL, status VARCHAR(20) NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, download_count INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, folder_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_document_status ON document (status)');
        $this->addSql('CREATE INDEX idx_document_search ON document USING GIN (search_vector)');
        $this->addSql('CREATE INDEX idx_document_title_trgm ON document USING GIN (title gin_trgm_ops)');
        $this->addSql('CREATE INDEX IDX_D8698A76162CB942 ON document (folder_id)');
        $this->addSql('CREATE TABLE document_tag (document_id UUID NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (document_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_D0234567C33F7837 ON document_tag (document_id)');
        $this->addSql('CREATE INDEX IDX_D0234567BAD26311 ON document_tag (tag_id)');
        $this->addSql('CREATE TABLE download_stat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day DATE NOT NULL, count INT NOT NULL, document_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_download_stat_day ON download_stat (document_id, day)');
        $this->addSql('CREATE INDEX IDX_3548C41DC33F7837 ON download_stat (document_id)');
        $this->addSql('CREATE TABLE folder (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_folder_slug ON folder (slug)');
        $this->addSql('CREATE INDEX IDX_ECA209CD727ACA70 ON folder (parent_id)');
        $this->addSql('CREATE TABLE share_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code_hash VARCHAR(255) NOT NULL, rotated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, rotated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CAD23D0124640BC0 ON share_code (rotated_by_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(60) NOT NULL, slug VARCHAR(70) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_tag_slug ON tag (slug)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, display_name VARCHAR(100) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, status VARCHAR(20) NOT NULL, totp_secret VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('ALTER TABLE audit_log ADD CONSTRAINT FK_F6E1C0F510DAF24A FOREIGN KEY (actor_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE change_request ADD CONSTRAINT FK_CB902D36C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE change_request ADD CONSTRAINT FK_CB902D369F23DA47 FOREIGN KEY (proposer_user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE change_request ADD CONSTRAINT FK_CB902D3670574616 FOREIGN KEY (reviewer_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76162CB942 FOREIGN KEY (folder_id) REFERENCES folder (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_tag ADD CONSTRAINT FK_D0234567C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_tag ADD CONSTRAINT FK_D0234567BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE download_stat ADD CONSTRAINT FK_3548C41DC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE folder ADD CONSTRAINT FK_ECA209CD727ACA70 FOREIGN KEY (parent_id) REFERENCES folder (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE share_code ADD CONSTRAINT FK_CAD23D0124640BC0 FOREIGN KEY (rotated_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');

        // Search vector maintained by the database: title (A), description and tags (B), content (C).
        $this->addSql(<<<'SQL'
            CREATE FUNCTION document_search_vector_update() RETURNS trigger AS $$
            BEGIN
                NEW.search_vector :=
                    setweight(to_tsvector('ariane_fr', coalesce(NEW.title, '')), 'A')
                    || setweight(to_tsvector('ariane_fr', coalesce(NEW.description, '')), 'B')
                    || setweight(to_tsvector('ariane_fr', coalesce(NEW.tags_text, '')), 'B')
                    || setweight(to_tsvector('ariane_fr', left(coalesce(NEW.extracted_text, ''), 1000000)), 'C');
                RETURN NEW;
            END
            $$ LANGUAGE plpgsql
            SQL);
        $this->addSql(<<<'SQL'
            CREATE TRIGGER document_search_vector_trigger
            BEFORE INSERT OR UPDATE OF title, description, tags_text, extracted_text ON document
            FOR EACH ROW EXECUTE FUNCTION document_search_vector_update()
            SQL);

        // Sessions (PdoSessionHandler).
        $this->addSql('CREATE TABLE sessions (sess_id VARCHAR(128) NOT NULL PRIMARY KEY, sess_data BYTEA NOT NULL, sess_lifetime INTEGER NOT NULL, sess_time INTEGER NOT NULL)');
        $this->addSql('CREATE INDEX sess_lifetime_idx ON sessions (sess_lifetime)');

        // Messenger (Doctrine transport).
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP TABLE sessions');
        $this->addSql('DROP TRIGGER document_search_vector_trigger ON document');
        $this->addSql('DROP FUNCTION document_search_vector_update()');
        $this->addSql('ALTER TABLE audit_log DROP CONSTRAINT FK_F6E1C0F510DAF24A');
        $this->addSql('ALTER TABLE change_request DROP CONSTRAINT FK_CB902D36C33F7837');
        $this->addSql('ALTER TABLE change_request DROP CONSTRAINT FK_CB902D369F23DA47');
        $this->addSql('ALTER TABLE change_request DROP CONSTRAINT FK_CB902D3670574616');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76162CB942');
        $this->addSql('ALTER TABLE document_tag DROP CONSTRAINT FK_D0234567C33F7837');
        $this->addSql('ALTER TABLE document_tag DROP CONSTRAINT FK_D0234567BAD26311');
        $this->addSql('ALTER TABLE download_stat DROP CONSTRAINT FK_3548C41DC33F7837');
        $this->addSql('ALTER TABLE folder DROP CONSTRAINT FK_ECA209CD727ACA70');
        $this->addSql('ALTER TABLE share_code DROP CONSTRAINT FK_CAD23D0124640BC0');
        $this->addSql('DROP TABLE audit_log');
        $this->addSql('DROP TABLE change_request');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE document_tag');
        $this->addSql('DROP TABLE download_stat');
        $this->addSql('DROP TABLE folder');
        $this->addSql('DROP TABLE share_code');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TEXT SEARCH CONFIGURATION ariane_fr');
    }
}
